### PR TITLE
rpc tests for net_version and web3_clientVersion

### PR DESCRIPTION
**Pull request by jorisbontje**

### CODE REVIEW

**Comment by frozeman** [comment]
Thanks, though i'm not sure yet what the version will actually look like, thats why i left them out.
I will merge later as soon as i know ;)

**Comment by frozeman** [comment]
Could you resolve the conflicts? I would like to merge it

**Comment by jorisbontje** [comment]
@frozeman I don't see the point in this anymore, as you already implemented these tests yourself back in March 27th: https://github.com/ethereum/rpc-tests/commit/1782536f8d2274cad0f055accf0638cd7fab9533

**Comment by frozeman** [comment]
alright, i forgot. thanks anyway.

**Pull request closed without merging**
